[arbitrum.address]
token = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
oft_messenger = "0x14E4A1B13bf7F943c8ff7C51fb60FA964A298D92"
src_periphery = "0x1235Ac1010FeeC8ae22744f323416cBBE37feDbE"

[999]
endpoint_url = "${NODE_URL_999}"

[999.address]
token = "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb"
oft_messenger = "0x904861a24F30EC96ea7CFC3bE9EA4B476d237e98"
dst_handler = "0x2beF20D17a17f6903017d27D1A35CC9Dc72b0888"
