[42161]
endpoint_url = "${NODE_URL_42161}"

[42161.address]
token = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
oft_messenger = "0x14E4A1B13bf7F943c8ff7C51fb60FA964A298D92"
src_periphery = "0xA0C112CEEF3d6322e066F6A64bf7dabaAc31F557"

[999]
endpoint_url = "${NODE_URL_999}"

[999.address]
token = "0xB8CE59FC3717ada4C02eaDF9682A9e934F625ebb"
oft_messenger = "0x904861a24F30EC96ea7CFC3bE9EA4B476d237e98"
dst_handler = "0x52a0c0D440baE2E9E5603C752a886f6622513769"
