[arbitrum]
endpoint_url = "${NODE_URL_42161}"

[arbitrum.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"

[arbitrum.uint]
cctpDomainId = 3

# Arbitrum Sepolia
[arbitrum-sepolia]
endpoint_url = "${NODE_URL_421614}"

[arbitrum-sepolia.address]
cctpTokenMessenger = "0x8FE6B999Dc680CcFDD5Bf7EB0974218be2542DAA"

[arbitrum-sepolia.uint]
cctpDomainId = 3


# HyperEVM testnet
[998]
endpoint_url = "${NODE_URL_998}"

[998.address]
cctpTokenMessenger = "0x8FE6B999Dc680CcFDD5Bf7EB0974218be2542DAA"
cctpMessageTransmitter = "0xE737e5cEBEEBa77EFE34D4aa090756590b1CE275"
# USDC
baseToken = "0x2B3370eE501B4a559b57D449569354196457D8Ab"

[998.uint]
cctpDomainId = 19
coreIndex = 0
accountActivationFeeCore = 100000000
bridgeSafetyBufferCore = 100000000

[998.bool]
canBeUsedForAccountActivation = true