[mainnet]
endpoint_url = "${NODE_URL_1}"

[mainnet.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
cctpMessageTransmitter = "0x81D40F21F12A8F0E3252Bccb954D722d4c464B64"
usdc = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
baseToken = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
# Placeholder for SponsoredCCTPDstPeriphery - update after deployment
sponsoredCCTPDstPeriphery = "0x5616194d65638086a3191B1fEF436f503ff329eC"
multicallHandler = "0x64a43393866DBA0044879979fAa7AD3d000622e9"
zkLighter = "0x3B4D794a66304F130a4Db8F2551B0070dfCf5ca7"

[mainnet.uint]
cctpDomainId = 0

[base]
endpoint_url = "${NODE_URL_8453}"

[base.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"

[base.uint]
cctpDomainId = 6

[arbitrum]
endpoint_url = "${NODE_URL_42161}"

[arbitrum.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
sponsoredCCTPSrcPeriphery = "0xAA4958EFa0Cf6DdD87e354a90785f1D7291a82c7"

[arbitrum.uint]
cctpDomainId = 3

[optimism]
endpoint_url = "${NODE_URL_10}"

[optimism.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85"

[optimism.uint]
cctpDomainId = 2

[unichain]
endpoint_url = "${NODE_URL_130}"

[unichain.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x078D782b760474a361dDA0AF3839290b0EF57AD6"

[unichain.uint]
cctpDomainId = 10

[world]
endpoint_url = "${NODE_URL_480}"

[world.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x79A02482A880bCE3F13e09Da970dC34db4CD24d1"

[world.uint]
cctpDomainId = 14

[linea]
endpoint_url = "${NODE_URL_59144}"

[linea.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x176211869cA2b568f2A7D4EE941E073a821EE1ff"

[linea.uint]
cctpDomainId = 11

[polygon]
endpoint_url = "${NODE_URL_137}"

[polygon.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359"

[polygon.uint]
cctpDomainId = 7

[143]
endpoint_url = "${NODE_URL_143}"

[143.address]
cctpTokenMessenger = "0x28b5a0e9C621a5BadaA536219b3a228C8168cf5d"
usdc = "0x754704Bc059F8C67012fEd69BC8A327a5aafb603"

[143.uint]
cctpDomainId = 15

# HyperEVM Mainnet
[999]
endpoint_url = "${NODE_URL_999}"

[999.address]
cctpMessageTransmitter = "0x81D40F21F12A8F0E3252Bccb954D722d4c464B64"
# USDC
baseToken = "0xb88339CB7199b77E23DB6E890353E22632Ba630f"

[999.uint]
cctpDomainId = 19
coreIndex = 0
accountActivationFeeCore = 100000000
bridgeSafetyBufferCore = 100000000

[999.bool]
canBeUsedForAccountActivation = true
