name: CI
on: [push]
jobs:
  build:
    name: Test-GasAnalytics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Additional dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get -y install rsync libudev-dev libusb-1.0-0-dev

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Test
        run: yarn test:gas-analytics
